travis:
  secure:
    BINSTAR_TOKEN: IYm9+zh5wiCdkVKzgL8JwREtvsrrbg4ikjpmSxVrDegvSvJvJBmG2HZIUBj/iCTZtjCa+itjStZa2DAKJcetJgISgAqnJfe90uY6h4Of3yIjonNsKE1HzevS+7whbpqh/WlZSdpLijF5nHMSLwwAAlfkESOg1r6rZVEM5UtHc9PVRbxSgkuScvEHxITPvfePeI3H6QZF0wWSTCmuhkZXkoKYDu1m3XpghzDdCLQcLJEEHs5di0b2k01C6VcNqjTq249CsbjHuo8QesqFULx8E9FU38rQuOkXO7Tb4Vh/eWLHewXVOODWIWppZFin8QWmvGcRnrAalJwdpaSODk7ez73YScbe9PQH/VNkz+yO+OmKIEx/A9xjgzpDiM4HlriECIdsJ1GIL/vBSubK0Pw3y4ETWu+crn9V24jqDBtrnpDObJTyfzYBLhBUJ86P3LEUjQHVpDzSyKcBSe3ljTKk8mFp5Itbh8O5xXSY7wzR413XpDwKn2ix1Vv1AxubRqBumHMooFTEgrU97nir9orr+6TKnXhOjjbeojXO9lY5bGhSo9nPA2tZHCxB+JqaIYmcO/HEpM5wAk0O/blHJHR3K/7vYGiMXD8zTrxreNWV+pNWuLSokarbrIbSS2ZV/5rSQjJr/cUHRh8eQBsDMbCbCoIThrVTn6IZM43ONbOcnD8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
