travis:
  secure:
    BINSTAR_TOKEN: dvfhLhmHQu9LOVDSGYt2mfK1BCbvcz3myz+obEqusnI5oQBB/vdtXI26EHOioxtdMp158rYdoTJqISkrhPuYplXSQ+a7BIGrkbbGrz0VJmKS04HQlZjf2vu45vac2+TCuSzXpvpTnpR8kkxo4xxYIZO7x6kkXA7TB36Zd0vJ6iDF6CFPJprJOg4JWfhXeJNezsr6sOHUuEN7gUw8FsxP3bA+3rvj5XEynky6Q744Z0Kn819PJY9DXF2sA5aUPA5jbBy6eH3+Yt1hzo9r9abrowCjdKgmnl/nEJ7DxdPtKbBIr/hSgTxgw0wZBcyoVbTa2KsliN259CmC8hm6PE4WP9lYqWFdqChy2NRgZf25K1DonGJ/q6mJHArEGAPmbjQcHZ/VWcGCfmtmFo++v501GPOxFjiCwHd1EIzuD5SqyX43YfHxVsX3qtJk9d0E9KyWkrjcwmQDqRbDXqeeVM/ueJSnmUmrvTbgQqx1SRHdxI3peGE3bqgMv/l8wnyqcP0EdMOMM9htbmgMygyElTxFwQ7eZaUAU9oLmGcAqG+/V3PnTDdApSJBC0vtdG4fT7Z9Fuh8VxMfhzJbwOr5dkhA7wyjauOqUtKq4WftpvhrHFwus/1jIvvodksBsywSdBD7++oTqYVql1kZbSFrmGA4gGjRbOGdHQvfZw+GjOdMHLU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
